// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net6_ApiModelo.Data;

#nullable disable

namespace Net6_ApiModelo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230418043307_TesteFolder")]
    partial class TesteFolder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Net6_ApiModelo.Model.Entities.Classes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdPersoagem")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdPersoagem");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Net6_ApiModelo.Model.Entities.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Personagem", (string)null);
                });

            modelBuilder.Entity("Net6_ApiModelo.Model.Entities.Classes", b =>
                {
                    b.HasOne("Net6_ApiModelo.Model.Entities.Personagem", "Personagem")
                        .WithMany("Classes")
                        .HasForeignKey("IdPersoagem")
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Net6_ApiModelo.Model.Entities.Personagem", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
